import {
  AcademicProgram,
  AnnouncementItem,
  NewsArticle,
  CollegeEvent,
  FacultyMember,
  Testimonial,
  ImpactStat,
  AdmissionApplication,
  StudentProfile,
  DownloadableResource,
  SermonLecture,
  FAQItem,
  AdminUser,
  ScrapbookItem,
  MigrationAuditItem,
} from './types';

export const INITIAL_ANNOUNCEMENTS: AnnouncementItem[] = [
  {
    id: 'ann-1',
    title: 'Admissions for Academic Year 2026–2027 are now officially open. Apply online today!',
    date: 'August 2026',
    category: 'Admissions',
    linkUrl: 'apply',
    isUrgent: true,
    active: true,
  },
  {
    id: 'ann-2',
    title: 'PCM 24th Annual National Theology & Ministry Conference scheduled for October 15–17, 2026.',
    date: 'August 2026',
    category: 'Conference',
    linkUrl: 'news-events',
    isUrgent: false,
    active: true,
  },
  {
    id: 'ann-3',
    title: 'Modular & Hybrid Master of Divinity cohorts begin September 2026. Limited slots available.',
    date: 'August 2026',
    category: 'Academic',
    linkUrl: 'academics',
    isUrgent: false,
    active: true,
  },
  {
    id: 'ann-4',
    title: 'Semestral Spiritual Retreat & Chapel Emphasis Week: "Faithful to the Heavenly Calling".',
    date: 'September 2026',
    category: 'Chapel',
    linkUrl: 'student-life',
    isUrgent: false,
    active: true,
  },
];

export const INITIAL_PROGRAMS: AcademicProgram[] = [
  {
    id: 'prog-shs-gas',
    name: 'Senior High School — General Academic Strand (GAS)',
    code: 'SHS-GAS',
    level: 'senior-high',
    duration: '2 Years (Grades 11 & 12)',
    credits: 80,
    studyMode: 'On-Campus Full-Time',
    shortDescription:
      'DepEd-accredited Senior High School program with Christian values integration, preparation for college theological and liberal arts courses, and full Government ESC Voucher support.',
    fullDescription:
      'Philippine College of Ministry offers the General Academic Strand (GAS) for Senior High School students seeking quality, Christ-centered education in the Cordillera and Baguio-La Trinidad area. Qualified Grade 10 completers from public schools and ESC participating private schools can study with zero to minimal tuition through DepEd vouchers.',
    objectives: [
      'Provide a solid academic foundation across humanities, social sciences, and natural sciences.',
      'Instill Christian character, moral integrity, and biblical discernment in adolescent youth.',
      'Prepare graduates seamlessly for collegiate theological education, pastoral training, or general higher education degrees.',
      'Offer leadership training, student ministry involvement, and community service activities.',
    ],
    curriculum: [
      {
        yearOrModule: 'Grade 11 (Core & Applied Subjects)',
        courses: [
          { code: 'GAS-101', title: 'Oral Communication & Reading and Writing Skills', units: 4 },
          { code: 'GAS-102', title: 'General Mathematics & Statistics and Probability', units: 4 },
          { code: 'GAS-103', title: 'Earth and Life Science / Physical Science', units: 4 },
          { code: 'GAS-104', title: 'Understanding Culture, Society and Politics', units: 4 },
          { code: 'GAS-105', title: 'Christian Values Education & Bible Survey I', units: 3 },
          { code: 'GAS-106', title: 'Physical Education and Health 1 & 2', units: 2 },
        ],
      },
      {
        yearOrModule: 'Grade 12 (Specialized Humanities & Applied Disciplines)',
        courses: [
          { code: 'GAS-201', title: 'Introduction to World Religions and Belief Systems', units: 4 },
          { code: 'GAS-202', title: 'Disciplines and Ideas in the Social Sciences', units: 4 },
          { code: 'GAS-203', title: 'Empowerment Technologies & Practical Research', units: 4 },
          { code: 'GAS-204', title: 'Philippine Politics and Governance', units: 4 },
          { code: 'GAS-205', title: 'Christian Ethics & Ministry Immersion', units: 3 },
          { code: 'GAS-206', title: 'Work Immersion / Culminating Activity', units: 4 },
        ],
      },
    ],
    careerOpportunities: [
      'Pathway to Bachelor of Theology (B.Th.) / BCM at PCM',
      'Entry to University Degree Programs (Education, Psychology, Communications)',
      'Youth Ministry and Campus Fellowship Leadership',
      'Christian School and Community Organization Staff',
    ],
    admissionRequirements: [
      'Grade 10 Report Card (Form 138) with Certificate of Completion',
      'DepEd Voucher Certificate (for Private School Completers) or Public School Diploma',
      'PSA Birth Certificate and Good Moral Character Certificate',
      'Parent/Guardian Consent and Student Interview',
    ],
    tuitionPerUnit: 0,
    featured: true,
  },
  {
    id: 'prog-assoc-th',
    name: 'Associate of Theology (A.Th.)',
    code: 'ATH-201',
    level: 'undergraduate',
    duration: '2 Years (4 Semesters)',
    credits: 68,
    studyMode: 'On-Campus Full-Time',
    shortDescription:
      'A two-year ministerial program specifically designed for associate ministry, local church workers, and ministry in rural or pioneering settings.',
    fullDescription:
      'The Associate of Theology provides focused biblical and practical ministry training for individuals preparing for rural ministry, assistant pastoral duties, and church planting. All units ladder directly into the four-year Bachelor of Theology program.',
    objectives: [
      'Master the foundational narratives and core doctrines of the Old and New Testaments.',
      'Develop practical skills in preaching, teaching, small group discipleship, and evangelism.',
      'Equip servants for rural and indigenous ministry contexts across northern Luzon and the Philippines.',
    ],
    curriculum: [
      {
        yearOrModule: 'First Year (Foundations)',
        courses: [
          { code: 'BIB-101', title: 'Old Testament Survey', units: 3 },
          { code: 'BIB-102', title: 'New Testament Survey', units: 3 },
          { code: 'THE-101', title: 'Introduction to Christian Doctrine', units: 3 },
          { code: 'HERM-101', title: 'Principles of Biblical Interpretation', units: 3 },
          { code: 'EVN-101', title: 'Evangelism and Discipleship in Rural Settings', units: 3 },
          { code: 'PRA-101', title: 'Weekend Ministry Practicum I', units: 2 },
        ],
      },
      {
        yearOrModule: 'Second Year (Ministry Application)',
        courses: [
          { code: 'HOM-201', title: 'Basic Homiletics and Preaching', units: 3 },
          { code: 'PAS-201', title: 'Pastoral Care in the Local Church', units: 3 },
          { code: 'HIS-201', title: 'Survey of Church History & Restoration Movement', units: 3 },
          { code: 'CED-201', title: 'Teaching the Bible to Children and Youth', units: 3 },
          { code: 'PRA-202', title: 'Field Ministry Practicum II (180 Hours)', units: 4 },
        ],
      },
    ],
    careerOpportunities: [
      'Associate / Assistant Pastor in Local Churches',
      'Rural Community Preacher and Pioneer Worker',
      'Church Sunday School Coordinator and Youth Leader',
      'Ladderized Entry to 3rd Year Bachelor of Theology',
    ],
    admissionRequirements: [
      'High School Diploma / Senior High School Certificate or equivalent',
      'Christian Testimony and Pastoral Endorsement Letter',
      'Entrance Assessment & Admissions Committee Interview',
    ],
    tuitionPerUnit: 1350,
    featured: true,
  },
  {
    id: 'prog-bth-scm',
    name: 'Bachelor of Arts in Theology, Specialized Chaplaincy Ministry (BTh SCM)',
    code: 'BTH-SCM-403',
    level: 'undergraduate',
    duration: '4 Years (8 Semesters)',
    credits: 142,
    studyMode: 'On-Campus Full-Time',
    shortDescription:
      'A specialized 4-year degree combining thorough biblical-theological grounding with intensive clinical pastoral education, crisis intervention, and institutional chaplaincy.',
    fullDescription:
      'The BTh Specialized Chaplaincy Ministry program equips dedicated ministers for institutional service in hospitals, military units, police detachments, correctional institutions, corporate settings, and emergency disaster relief organizations.',
    objectives: [
      'Provide sound biblical exegesis and systematic theology for multi-cultural institutional environments.',
      'Develop competencies in Clinical Pastoral Education (CPE), grief therapy, and trauma counseling.',
      'Understand civil protocols, ethics, and chaplaincy policies in government, uniformed services, and corporate settings.',
      'Cultivate empathetic, compassionate ministry to suffering and marginalized populations.',
    ],
    curriculum: [
      {
        yearOrModule: 'First & Second Year (Theological & Counseling Foundations)',
        courses: [
          { code: 'BIB-101', title: 'Old & New Testament Exegesis', units: 6 },
          { code: 'THE-201', title: 'Systematic Theology & Ethics', units: 6 },
          { code: 'CHP-101', title: 'Introduction to Institutional Chaplaincy', units: 3 },
          { code: 'PSY-201', title: 'Developmental Psychology & Pastoral Counseling', units: 3 },
        ],
      },
      {
        yearOrModule: 'Third & Fourth Year (Clinical Chaplaincy & Practicum)',
        courses: [
          { code: 'CHP-301', title: 'Hospital & Healthcare Chaplaincy (Clinical Pastoral Care)', units: 3 },
          { code: 'CHP-302', title: 'Military, Police & Uniformed Services Ministry', units: 3 },
          { code: 'CHP-401', title: 'Prison, Correctional & Crisis De-escalation Care', units: 3 },
          { code: 'PRA-490', title: 'Supervised Hospital / Institutional Residency (300 Hours)', units: 6 },
        ],
      },
    ],
    careerOpportunities: [
      'Hospital and Hospice Healthcare Chaplain',
      'Military and Police Service Chaplain',
      'Correctional Institution & Prison Chaplain',
      'Corporate and Industrial Workplace Chaplain',
      'Disaster Relief and Trauma Response Counselor',
    ],
    admissionRequirements: [
      'High School / Senior High School Graduate with good moral character',
      'Written testimony of calling to institutional and compassionate service',
      'Pastoral and Character Recommendation Letters',
      'Psychological Assessment and Faculty Admissions Panel Interview',
    ],
    tuitionPerUnit: 1500,
    featured: true,
  },
  {
    id: 'prog-bth',
    name: 'Bachelor of Theology (B.Th.)',
    code: 'BTH-401',
    level: 'undergraduate',
    duration: '4 Years (8 Semesters)',
    credits: 138,
    studyMode: 'On-Campus Full-Time',
    shortDescription:
      'A comprehensive four-year ministerial degree grounding students in biblical languages (Greek & Hebrew), systematic theology, expository preaching, and pastoral leadership.',
    fullDescription:
      'The Bachelor of Theology program is designed for individuals called to full-time pastoral ministry, church planting, biblical teaching, and missionary service. It combines rigorous biblical and theological training with field practicum and spiritual formation, preparing faithful shepherds for the local church and the global harvest field.',
    objectives: [
      'Master the Old and New Testaments in their historical, grammatical, and canonical contexts.',
      'Demonstrate proficiency in biblical Greek and basic biblical Hebrew for exegetical accuracy.',
      'Articulate a coherent, historic Reformed/Evangelical systematic theology grounded in Scripture.',
      'Develop practical competence in expository preaching, pastoral counseling, and church administration.',
      'Cultivate Christ-like character, spiritual disciplines, and servant leadership.',
    ],
    curriculum: [
      {
        yearOrModule: 'First Year (Foundations)',
        courses: [
          { code: 'BIB-101', title: 'Old Testament Survey', units: 3 },
          { code: 'BIB-102', title: 'New Testament Survey', units: 3 },
          { code: 'GRK-101', title: 'Biblical Greek Grammar I', units: 3 },
          { code: 'THE-101', title: 'Introduction to Christian Doctrine', units: 3 },
          { code: 'MIN-101', title: 'Spiritual Formation & Discipleship', units: 3 },
          { code: 'ENG-101', title: 'Academic Research & Theological Writing', units: 3 },
        ],
      },
      {
        yearOrModule: 'Second Year (Exegesis & Languages)',
        courses: [
          { code: 'GRK-201', title: 'Greek Syntax & Exegesis', units: 3 },
          { code: 'HEB-101', title: 'Biblical Hebrew Grammar I', units: 3 },
          { code: 'HERM-201', title: 'Biblical Hermeneutics', units: 3 },
          { code: 'THE-201', title: 'Systematic Theology I (God, Creation, Humanity)', units: 3 },
          { code: 'HIS-201', title: 'Church History I (Early & Medieval)', units: 3 },
          { code: 'PRA-201', title: 'Ministry Practicum I (Local Church Service)', units: 2 },
        ],
      },
      {
        yearOrModule: 'Third Year (Theology & Pastoral Arts)',
        courses: [
          { code: 'THE-301', title: 'Systematic Theology II (Christology, Pneumatology, Soteriology)', units: 3 },
          { code: 'HOM-301', title: 'Expository Preaching & Homiletics', units: 3 },
          { code: 'PAS-301', title: 'Pastoral Ministry & Church Administration', units: 3 },
          { code: 'MIS-301', title: 'Theology of World Missions & Evangelism', units: 3 },
          { code: 'ETH-301', title: 'Christian Ethics in Contemporary Society', units: 3 },
          { code: 'PRA-301', title: 'Ministry Practicum II (Apprenticeship)', units: 2 },
        ],
      },
      {
        yearOrModule: 'Fourth Year (Advanced Ministry & Capstone)',
        courses: [
          { code: 'THE-401', title: 'Systematic Theology III (Ecclesiology & Eschatology)', units: 3 },
          { code: 'APO-401', title: 'Christian Apologetics & World Religions', units: 3 },
          { code: 'COU-401', title: 'Biblical Counseling & Family Care', units: 3 },
          { code: 'MIN-402', title: 'Church Planting & Urban Ministry in the Philippines', units: 3 },
          { code: 'SEM-499', title: 'Senior Theological Thesis / Ministry Capstone', units: 4 },
          { code: 'PRA-401', title: 'Full-Year Pastoral Residency & Internship', units: 4 },
        ],
      },
    ],
    careerOpportunities: [
      'Senior / Associate Pastor in Local Churches',
      'Cross-Cultural Missionary & Church Planter',
      'Bible Teacher & Christian School Educator',
      'Youth & Family Ministry Director',
      'Campus Evangelism & Discipleship Worker',
      'Preparation for Master of Divinity (M.Div.) Studies',
    ],
    admissionRequirements: [
      'High School Diploma or DepEd/CHED Equivalent Transcript',
      'Personal Testimony of Faith in the Lord Jesus Christ',
      'Pastoral Recommendation from home church pastor',
      'Passing score in PCM Bible Knowledge & English Proficiency Exam',
      'Formal Admission Interview with the Faculty Admissions Committee',
    ],
    tuitionPerUnit: 1450,
    featured: true,
  },
  {
    id: 'prog-bcm',
    name: 'Bachelor of Christian Ministry (B.C.M.)',
    code: 'BCM-402',
    level: 'undergraduate',
    duration: '4 Years (8 Semesters)',
    credits: 132,
    studyMode: 'On-Campus Full-Time',
    shortDescription:
      'A practice-oriented ministry degree focusing on discipleship, worship leadership, Christian education, community development, and church organizational management.',
    fullDescription:
      'The Bachelor of Christian Ministry prepares holistic ministry leaders capable of mobilizing church departments, leading contemporary discipleship movements, organizing compassionate community outreaches, and directing non-profit Christian agencies throughout the Philippines and Southeast Asia.',
    objectives: [
      'Equip leaders with solid biblical interpretation and theological understanding.',
      'Develop competencies in leadership dynamics, team mobilization, and ministry governance.',
      'Cultivate specialized skills in Christian education, youth ministries, and community development.',
      'Integrate faith and compassionate outreach to address societal brokenness.',
    ],
    curriculum: [
      {
        yearOrModule: 'First & Second Year (Biblical Foundations)',
        courses: [
          { code: 'BIB-101', title: 'Old & New Testament Introductions', units: 6 },
          { code: 'THE-101', title: 'Christian Doctrine & Worldview', units: 3 },
          { code: 'CED-101', title: 'Principles of Christian Education', units: 3 },
          { code: 'LEA-201', title: 'Biblical Servant Leadership', units: 3 },
          { code: 'PRA-101', title: 'Field Ministry Practicum', units: 4 },
        ],
      },
      {
        yearOrModule: 'Third & Fourth Year (Advanced Ministry Practice)',
        courses: [
          { code: 'YTH-301', title: 'Next-Generation & Youth Ministry', units: 3 },
          { code: 'WOR-301', title: 'Theology of Christian Worship & Liturgy', units: 3 },
          { code: 'COM-401', title: 'Community Development & Holistic Missions', units: 3 },
          { code: 'NPO-401', title: 'Non-Profit Management & Church Finance', units: 3 },
          { code: 'CAP-499', title: 'Integrated Ministry Project & Internship', units: 6 },
        ],
      },
    ],
    careerOpportunities: [
      'Church Ministry Coordinator & Administrator',
      'Christian Education Director',
      'Youth & Campus Ministry Pastor',
      'NGO & Christian Non-Profit Program Manager',
      'Community Outreach & Relief Coordinator',
    ],
    admissionRequirements: [
      'High School Report Card (Form 138) / Transcript of Records',
      'Born-Again Christian with minimum 2 years active church involvement',
      'Pastor & Church Leader Endorsement Letters',
      'Admissions Interview & Christian Service Evaluation',
    ],
    tuitionPerUnit: 1400,
    featured: true,
  },
  {
    id: 'prog-mdiv',
    name: 'Master of Divinity (M.Div.)',
    code: 'MDIV-801',
    level: 'graduate',
    duration: '3 Years (Full-Time) / 4–5 Years (Modular Hybrid)',
    credits: 90,
    studyMode: 'Modular / Hybrid',
    shortDescription:
      'The premier professional graduate theological degree designed for pastors, scholars, and church leaders seeking in-depth original language exegesis, advanced theology, and strategic ministry leadership.',
    fullDescription:
      'The Master of Divinity at PCM is designed to produce scholarly pastors and visionary kingdom leaders. Offered in both resident and flexible modular formats for bi-vocational and active ministry practitioners, the program integrates advanced Hebrew and Greek exegesis, historical-dogmatic theology, and contemporary contextual application for the Philippine and Asian ministry landscapes.',
    objectives: [
      'Conduct rigorous grammatical-historical exegesis of Old and New Testament Scriptures in original languages.',
      'Synthesize biblical, historical, and systematic theology to formulate sound theological paradigms.',
      'Execute high-level expository preaching and persuasive pastoral communication.',
      'Lead congregations through revitalization, strategic mission initiatives, and complex ethical challenges.',
    ],
    curriculum: [
      {
        yearOrModule: 'Core Exegesis & Biblical Studies',
        courses: [
          { code: 'OT-501', title: 'Advanced Old Testament Theology & Exegesis', units: 3 },
          { code: 'NT-501', title: 'Advanced New Testament Theology & Greek Exegesis', units: 3 },
          { code: 'HEB-501', title: 'Hebrew Exegetical Methods in Prophetic Literature', units: 3 },
          { code: 'GRK-501', title: 'Pauline Epistles Greek Exegesis', units: 3 },
        ],
      },
      {
        yearOrModule: 'Historical & Systematic Theology',
        courses: [
          { code: 'ST-601', title: 'Advanced Dogmatics: Doctrine of God & Trinity', units: 3 },
          { code: 'ST-602', title: 'Covenant Theology & Dispensational Perspectives', units: 3 },
          { code: 'CH-601', title: 'History of the Church & Philippine Evangelical Movement', units: 3 },
          { code: 'AP-601', title: 'Contemporary Apologetics & Cultural Engagement', units: 3 },
        ],
      },
      {
        yearOrModule: 'Pastoral Praxis & Thesis',
        courses: [
          { code: 'PR-701', title: 'Advanced Expository Homiletics', units: 3 },
          { code: 'PC-701', title: 'Pastoral Counseling & Crisis Intervention', units: 3 },
          { code: 'ML-701', title: 'Strategic Leadership & Church Governance', units: 3 },
          { code: 'TH-799', title: 'Master of Divinity Thesis / Major Expository Project', units: 6 },
        ],
      },
    ],
    careerOpportunities: [
      'Senior Pastor & Preaching Minister',
      'Theological Seminary / Bible College Professor',
      'Denominational Director / Bishop / Overseer',
      'Military, Hospital, or Corporate Chaplain',
      'Doctor of Ministry (D.Min.) / Ph.D. in Theology Candidate',
    ],
    admissionRequirements: [
      'Bachelor’s Degree from an accredited college or university (any discipline)',
      'Official Transcript of Records with GPA 2.5 or better',
      'Written Statement of Christian Faith and Calling into Pastoral/Theological Ministry',
      'Three Recommendation Letters (Pastor, Academic Professor, Ministry Colleague)',
      'Theological Admissions Writing Assessment & Faculty Interview',
    ],
    tuitionPerUnit: 1850,
    featured: true,
  },
  {
    id: 'prog-mcl',
    name: 'Master of Christian Leadership (M.C.L.)',
    code: 'MCL-802',
    level: 'graduate',
    duration: '2 Years (4 Semesters / Weekend Cohorts)',
    credits: 48,
    studyMode: 'Evening & Weekend',
    shortDescription:
      'A professional master’s degree empowering marketplace professionals, ministry directors, and church board elders with kingdom leadership models and organizational wisdom.',
    fullDescription:
      'Designed specifically for working professionals, marketplace ministers, and senior church leaders, the MCL combines biblical principles of governance, ethical stewardship, conflict transformation, and visionary strategic planning to multiply kingdom impact across sectors.',
    objectives: [
      'Integrate biblical theology with organizational leadership principles.',
      'Develop emotional intelligence, spiritual maturity, and team-building capacities.',
      'Master financial stewardship, legal compliance, and strategic board governance.',
      'Cultivate impactful ministry leadership in corporate, ecclesiastical, and civil sectors.',
    ],
    curriculum: [
      {
        yearOrModule: 'Year 1 (Leadership Core)',
        courses: [
          { code: 'LDR-501', title: 'Biblical Foundations of Leadership', units: 3 },
          { code: 'ORG-502', title: 'Organizational Behavior & Church Culture', units: 3 },
          { code: 'ETH-503', title: 'Executive Ethics & Corporate Integrity', units: 3 },
          { code: 'STR-504', title: 'Strategic Visioning & Change Management', units: 3 },
        ],
      },
      {
        yearOrModule: 'Year 2 (Applied Kingdom Leadership)',
        courses: [
          { code: 'GOV-601', title: 'Church Governance, Policy & Risk Management', units: 3 },
          { code: 'CNF-602', title: 'Conflict Resolution & Peacemaking', units: 3 },
          { code: 'MKP-603', title: 'Marketplace Ministry & Faith at Work', units: 3 },
          { code: 'CAP-699', title: 'Organizational Transformation Capstone Project', units: 6 },
        ],
      },
    ],
    careerOpportunities: [
      'Executive Pastor / Church Business Administrator',
      'Marketplace Ministry Director & Chaplain',
      'Christian School / College Administrator',
      'Faith-Based NGO Executive Director',
      'Church Board Chairman / Elder Board Member',
    ],
    admissionRequirements: [
      'Bachelor\'s Degree in any field from an accredited institution',
      'Minimum 2 years of recognized leadership or professional experience',
      'Endorsement from Home Church Senior Pastor',
      'Admissions Interview with Program Director',
    ],
    tuitionPerUnit: 1800,
    featured: false,
  },
  {
    id: 'prog-dip',
    name: 'Diploma in Ministry (Dip.Min.)',
    code: 'DIP-201',
    level: 'diploma',
    duration: '2 Years (4 Semesters)',
    credits: 64,
    studyMode: 'On-Campus Full-Time',
    shortDescription:
      'A practical two-year diploma program providing essential foundational Bible survey, evangelism, teaching methods, and ministry practicum.',
    fullDescription:
      'The Diploma in Ministry is ideal for local church workers, lay leaders, and ministry assistants seeking sound biblical foundation and hands-on ministerial skills in an accelerated timeframe. All units earned ladder seamlessly into the Bachelor of Theology program.',
    objectives: [
      'Provide solid understanding of the entire biblical narrative.',
      'Equip students with practical evangelism, discipleship, and teaching skills.',
      'Instill spiritual disciplines and love for the local church body.',
    ],
    curriculum: [
      {
        yearOrModule: 'Full 2-Year Program',
        courses: [
          { code: 'BIB-101', title: 'Old & New Testament Survey', units: 6 },
          { code: 'THE-101', title: 'Essential Christian Doctrines', units: 3 },
          { code: 'EVN-101', title: 'Personal Evangelism & Discipleship', units: 3 },
          { code: 'MIN-201', title: 'Church Leadership & Small Group Dynamics', units: 3 },
          { code: 'PRA-200', title: 'Field Ministry Practicum (120 Hours)', units: 4 },
        ],
      },
    ],
    careerOpportunities: [
      'Lay Preacher & Small Group Overseer',
      'Assistant Pastor & Ministry Worker',
      'Church Sunday School Superintendent',
      'Church Outreach Worker',
    ],
    admissionRequirements: [
      'High School Graduate or equivalent',
      'Testimony of Salvation and Church Membership',
      'Pastoral Letter of Endorsement',
    ],
    tuitionPerUnit: 1300,
    featured: false,
  },
  {
    id: 'prog-cert',
    name: 'Certificate in Biblical Studies (C.B.S.)',
    code: 'CBS-101',
    level: 'certificate',
    duration: '1 Year (2 Semesters / Modular)',
    credits: 30,
    studyMode: 'Online & Modular',
    shortDescription:
      'An accessible 1-year foundational certificate covering Old & New Testament surveys, basic hermeneutics, personal discipleship, and Christian worldview.',
    fullDescription:
      'Perfect for Sunday school teachers, cell group leaders, professionals, and church volunteers who desire systematic Bible knowledge without enrolling in a multi-year degree. Fully available in flexible modular and online formats.',
    objectives: [
      'Understand the broad scope and redemptive themes of the Bible.',
      'Learn how to properly read, interpret, and apply the Scriptures.',
      'Deepen personal devotion, prayer life, and spiritual vitality.',
    ],
    curriculum: [
      {
        yearOrModule: 'Semester 1 & 2 Modules',
        courses: [
          { code: 'BIB-01', title: 'How to Study the Bible (Hermeneutics for Laymen)', units: 3 },
          { code: 'BIB-02', title: 'Old Testament Essentials', units: 3 },
          { code: 'BIB-03', title: 'New Testament Essentials', units: 3 },
          { code: 'THE-01', title: 'Core Beliefs of Christianity', units: 3 },
          { code: 'MIN-01', title: 'Practical Discipleship in Daily Life', units: 3 },
        ],
      },
    ],
    careerOpportunities: [
      'Small Group / Bible Study Leader',
      'Sunday School Teacher & Youth Counselor',
      'Equipped Lay Servant in Local Church',
      'Foundation for Diploma / Degree Programs',
    ],
    admissionRequirements: [
      'Open to all born-again believers with high school diploma or equivalent',
      'Recommendation from Church Pastor / Elder',
    ],
    tuitionPerUnit: 1200,
    featured: true,
  },
  {
    id: 'prog-grad-cert',
    name: 'Graduate Certificate in Theological Studies',
    code: 'GCTS-501',
    level: 'graduate',
    duration: '1 Year (Modular / Hybrid)',
    credits: 24,
    studyMode: 'Modular / Hybrid',
    shortDescription:
      'A focused post-baccalaureate certificate providing graduate-level theological and hermeneutical training for bi-vocational leaders and ministry specialists.',
    fullDescription:
      'The Graduate Certificate in Theological Studies offers concentrated graduate courses for degreed individuals seeking theological enrichment or transitioning into formal ministry. All 24 units transfer directly into the Master of Divinity program.',
    objectives: [
      'Engage with advanced biblical interpretation and theological reflection.',
      'Evaluate cultural issues through a rigorous Reformed and Evangelical framework.',
      'Strengthen teaching ministries within local church communities.',
    ],
    curriculum: [
      {
        yearOrModule: 'Graduate Modules',
        courses: [
          { code: 'ST-501', title: 'Systematic Theology Overview', units: 3 },
          { code: 'BT-502', title: 'Biblical Theology of Redemption', units: 3 },
          { code: 'AP-503', title: 'Christian Apologetics & Cultural Engagement', units: 3 },
          { code: 'EX-504', title: 'Advanced Hermeneutics & Exegetical Principles', units: 3 },
        ],
      },
    ],
    careerOpportunities: [
      'Theological Educator in Local Churches',
      'Christian Ministry Director',
      'Direct Pathway to Master of Divinity (M.Div.)',
    ],
    admissionRequirements: [
      'Recognized Bachelor\'s Degree in any discipline',
      'Christian Testimony & Pastoral Recommendation',
    ],
    tuitionPerUnit: 1800,
    featured: false,
  },
];

export const INITIAL_NEWS: NewsArticle[] = [
  {
    id: 'news-1',
    slug: 'pcm-opens-admissions-ay-2026-2027',
    title: 'PCM Opens Admissions for Academic Year 2026–2027 with Expanded Scholarship Grants',
    category: 'Academic',
    date: 'August 18, 2026',
    author: 'Office of the Registrar & Admissions',
    readTime: '4 min read',
    excerpt:
      'Philippine College of Ministry has officially launched its online application portal for incoming undergraduate and graduate students for the 2026–2027 academic year, offering full and partial tuition scholarships for pastoral candidates.',
    content:
      'QUEZON CITY, PHILIPPINES — Philippine College of Ministry (PCM) is pleased to announce that applications for Academic Year 2026–2027 are now open. As part of PCM’s continuing commitment to equip servants for Kingdom impact across the archipelago, the Board of Trustees has approved an expanded ministerial scholarship grant allocating support for prospective pastors, church planters, and children of full-time ministry workers.\n\nProspective students may now complete the entire admissions process through the newly launched PCM Online Admissions Portal, which includes direct document uploading, recommendation tracking, and interview scheduling. Degree offerings include the flagship Bachelor of Theology (B.Th.), Bachelor of Christian Ministry (B.C.M.), Master of Divinity (M.Div.), and Master of Christian Leadership (M.C.L.). Modular formats are available for bi-vocational workers.\n\n"Our nation and the global harvest field are in urgent need of shepherds who are deeply grounded in the infallible Word of God, spiritually vibrant, and culturally effective," said Academic Dean Dr. Emmanuel Santos. "PCM is ready to welcome the next generation of gospel servants."',
    imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=1200&auto=format&fit=crop',
    featured: true,
    tags: ['Admissions', 'Scholarships', 'Enrollment', 'Academic Year 2026'],
  },
  {
    id: 'news-2',
    slug: 'new-theological-faculty-members-join-pcm',
    title: 'PCM Welcomes Renowned Biblical Scholars to the Academic Faculty',
    category: 'Academic',
    date: 'August 05, 2026',
    author: 'Office of Academic Affairs',
    readTime: '3 min read',
    excerpt:
      'PCM strengthens its academic roster with the appointment of Dr. Jonathan Reyes (Ph.D. Old Testament, Trinity Evangelical) and Prof. Maria Grace Morales (Th.M. Systematic Theology) for the upcoming term.',
    content:
      'The Board of Trustees and the President’s Council are delighted to introduce two distinguished additions to the PCM resident faculty. Dr. Jonathan Reyes joins as Professor of Old Testament and Biblical Hebrew, bringing over fifteen years of scholarly research and pastoral experience. Prof. Maria Grace Morales joins the Department of Theology and Christian Education.\n\nTheir appointments reinforce PCM’s commitment to academic rigor combined with warm pastoral piety, ensuring our students receive world-class theological instruction right here in the Philippines.',
    imageUrl: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?q=80&w=1200&auto=format&fit=crop',
    featured: true,
    tags: ['Faculty', 'Old Testament', 'Theology', 'Academic Excellence'],
  },
  {
    id: 'news-3',
    slug: 'students-participate-in-community-ministry',
    title: 'PCM Ministry Practicum Students Lead Medical & Spiritual Outreach in Rizal Province',
    category: 'Ministry',
    date: 'July 28, 2026',
    author: 'Department of Practical Ministry & Missions',
    readTime: '5 min read',
    excerpt:
      'Over 60 PCM theology and ministry students partnered with local evangelical churches in Rodriguez, Rizal to provide medical consultations, children’s vacation Bible schools, and community evangelism.',
    content:
      'True theological education does not remain in the classroom; it overflows into compassionate service. Last weekend, students enrolled in the PCM Ministry Practicum program executed a comprehensive community outreach in partnership with five local churches in Rizal.\n\nThe team served over 450 families through free health screenings, distributed food packs and gospel literature, conducted an interactive Vacation Bible School for 200 children, and saw dozens of local residents respond to the Gospel of Jesus Christ. Practicum coordinator Pastor David Tan remarked, "Watching our young ministers pray with weeping mothers and teach children with gentleness confirms that God is molding their shepherd hearts."',
    imageUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?q=80&w=1200&auto=format&fit=crop',
    featured: true,
    tags: ['Practicum', 'Outreach', 'Missions', 'Community Service'],
  },
  {
    id: 'news-4',
    slug: 'pcm-hosts-annual-theology-conference-2026',
    title: 'Registration Opens for 2026 National Theology Conference: "Unshakable Word in Shifting Times"',
    category: 'Spiritual Formation',
    date: 'July 14, 2026',
    author: 'PCM Events Committee',
    readTime: '4 min read',
    excerpt:
      'Pastors, seminary educators, and church workers nationwide are invited to the 2026 PCM National Theology Conference on October 15–17, featuring plenary lectures on biblical inerrancy, hermeneutics, and cultural engagement.',
    content:
      'PCM is thrilled to open early-bird registration for the 2026 National Theology Conference. This three-day intensive summit gathers over 400 church leaders and theological educators from Luzon, Visayas, and Mindanao for deep theological reflection, mutual encouragement, and united prayer.\n\nPlenary topics will address defending the historical authority of Scripture, navigating post-modern ethical challenges, biblical ecclesiology in urban centers, and reviving expository preaching in the local church. Early registrants receive discounted rates and access to all conference recordings and printed monographs.',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=1200&auto=format&fit=crop',
    featured: false,
    tags: ['Conference', 'Theology', 'Pastors Summit', 'Preaching'],
  },
  {
    id: 'news-5',
    slug: 'ministry-practicum-program-begins',
    title: 'Over 80 Churches Partner with PCM for 2026–2027 Pastoral Apprenticeship Program',
    category: 'Ministry',
    date: 'June 30, 2026',
    author: 'Office of Church Partnerships',
    readTime: '3 min read',
    excerpt:
      'PCM expands its formal church partnership network to 80+ evangelical congregations across Metro Manila, Bulacan, Cavite, and Laguna, ensuring every student receives direct pastoral mentorship.',
    content:
      'PCM firmly believes that the seminary exists to serve the local church. Under the enhanced Pastoral Apprenticeship Program, every third and fourth-year student is placed under the direct supervision of an experienced senior pastor for weekly hands-on ministry, pulpit preaching, counseling observation, and elder board meeting immersion.',
    imageUrl: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?q=80&w=1200&auto=format&fit=crop',
    featured: false,
    tags: ['Church Partnerships', 'Apprenticeship', 'Pastoral Training'],
  },
  {
    id: 'news-6',
    slug: 'chapel-week-2026-spiritual-renewal',
    title: 'Semestral Chapel Week Brings Profound Spiritual Renewal to Campus Community',
    category: 'Campus Life',
    date: 'June 12, 2026',
    author: 'Chapel & Spiritual Life Committee',
    readTime: '3 min read',
    excerpt:
      'The PCM campus paused academic lectures for three sacred days of continuous prayer, fasting, and biblical preaching centered on the theme "Pursuing Holiness in the Holy Spirit".',
    content:
      'The entire PCM community experienced a deeply moving season of spiritual rejuvenation during the annual Semestral Chapel Week. Faculty, staff, resident students, and modular attendees gathered each morning and evening for acoustic worship, student testimonies, and expository messages on 1 Peter.',
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1200&auto=format&fit=crop',
    featured: false,
    tags: ['Chapel', 'Spiritual Renewal', 'Worship', 'Prayer'],
  },
];

export const INITIAL_EVENTS: CollegeEvent[] = [
  {
    id: 'evt-1',
    title: 'PCM 2026 National Theology Conference',
    date: 'October 15–17, 2026',
    time: '8:30 AM – 5:00 PM PST',
    location: 'PCM Main Auditorium, Quezon City & Livestream',
    category: 'Conference',
    description:
      'A three-day gathering of pastors, theologians, and church leaders exploring the authority and application of Scripture in modern Philippine society.',
    speaker: 'Dr. Timothy Keller Memorial Lecturer & PCM Faculty',
    featured: true,
    registrationOpen: true,
    registrationFee: '₱1,500 (Early Bird) / ₱2,000 (Regular)',
    maxAttendees: 500,
    registeredCount: 342,
  },
  {
    id: 'evt-2',
    title: 'Ministry Leadership Summit: Shepherding in Times of Crisis',
    date: 'September 19, 2026',
    time: '9:00 AM – 4:00 PM PST',
    location: 'PCM Grace Chapel & Zoom Interactive Cohort',
    category: 'Seminar',
    description:
      'Equipping pastors, elders, and ministry coordinators with practical frameworks for conflict resolution, financial resilience, and crisis counseling.',
    speaker: 'Bishop Samuel Dela Cruz & Rev. Dr. Emmanuel Santos',
    featured: true,
    registrationOpen: true,
    registrationFee: '₱500 (Includes lunch & workbook)',
    maxAttendees: 200,
    registeredCount: 168,
  },
  {
    id: 'evt-3',
    title: 'New Student Orientation & Convocation Service (AY 2026–2027)',
    date: 'September 01, 2026',
    time: '9:00 AM – 1:00 PM PST',
    location: 'PCM Main Chapel Hall',
    category: 'Orientation',
    description:
      'Welcoming incoming undergraduate and graduate students, introducing faculty mentors, campus resources, and commissioning in prayer.',
    speaker: 'President Dr. Benjamin Villanueva',
    featured: true,
    registrationOpen: true,
    registrationFee: 'Free for Enrolled Students',
    maxAttendees: 300,
    registeredCount: 215,
  },
  {
    id: 'evt-4',
    title: 'Biblical Studies Seminar: Exegesis of the Book of Romans',
    date: 'November 07, 2026',
    time: '1:00 PM – 6:00 PM PST',
    location: 'PCM Seminar Room 201 & Online',
    category: 'Seminar',
    description:
      'An intensive theological and exegetical study of the core doctrines of justification, sanctification, and election in Romans 1–8.',
    speaker: 'Dr. Jonathan Reyes, Ph.D.',
    featured: false,
    registrationOpen: true,
    registrationFee: '₱350',
    maxAttendees: 120,
    registeredCount: 88,
  },
  {
    id: 'evt-5',
    title: 'Semestral Spiritual Retreat & Day of Prayer',
    date: 'November 20, 2026',
    time: '7:30 AM – 5:00 PM PST',
    location: 'PCM Prayer Mountain & Prayer Garden',
    category: 'Retreat',
    description:
      'A dedicated day away from academic deadlines to seek the Lord in silence, Scripture meditation, intercession, and communal worship.',
    speaker: 'Pastor David Tan & Student Ministry Team',
    featured: false,
    registrationOpen: true,
    registrationFee: '₱250 (Transportation & Meals)',
    maxAttendees: 150,
    registeredCount: 110,
  },
];

export const INITIAL_FACULTY: FacultyMember[] = [
  {
    id: 'fac-bot-laruta',
    name: 'Atty. Joseph Michael Laruta',
    title: 'Chairman, Board of Trustees',
    group: 'Board of Trustees',
    role: 'Board of Trustees',
    credentials: 'B.A. Classical Philosophy (PUP), M.A. Philosophy (DLSU), Bachelor of Law (San Sebastian College of Law)',
    degrees: [
      'Bachelor of Arts in Classical Philosophy, Polytechnic University of the Philippines',
      'Master of Arts in Philosophy, De La Salle University',
      'Bachelor of Law, San Sebastian College of Law',
    ],
    bio: 'Chairman, Board of Trustees. Practicing Lawyer in Zambales.',
    coursesTaught: ['Christian Philosophy & Jurisprudence', 'Institutional Governance & Ethics'],
    imageUrl: '',
    email: 'laruta.trustee@pcm.ph',
    featured: true,
  },
  {
    id: 'fac-bot-ali',
    name: 'Arch. Caesar J. Ali',
    title: 'Vice Chairman, Board of Trustees',
    group: 'Board of Trustees',
    role: 'Board of Trustees',
    credentials: 'Vice Chairman, Board of Trustees',
    degrees: ['Bachelor of Science in Architecture'],
    bio: 'Vice Chairman, Board of Trustees.',
    coursesTaught: ['Campus Planning & Infrastructure Advisory', 'Board Governance'],
    imageUrl: '',
    email: 'ali.trustee@pcm.ph',
    featured: false,
  },
  {
    id: 'fac-bot-batuna',
    name: 'Jessie Batuna',
    title: 'Secretary, Board of Trustees',
    group: 'Board of Trustees',
    role: 'Board of Trustees',
    credentials: 'Bachelor of Arts in Christian Ministry - 1997',
    degrees: ['Bachelor of Arts in Christian Ministry - 1997'],
    bio: 'Secretary, Board of Trustees.',
    coursesTaught: ['Christian Ministry Foundations', 'Church Governance'],
    imageUrl: '',
    email: 'batuna.trustee@pcm.ph',
    featured: false,
  },
  {
    id: 'fac-bot-aliba',
    name: 'Arch. Roland Aliba',
    title: 'Treasurer, Board of Trustees',
    group: 'Board of Trustees',
    role: 'Board of Trustees',
    credentials: 'Bachelor of Science in Architecture, Autocad Drafting and Design',
    degrees: ['Bachelor of Science in Architecture'],
    bio: 'Treasurer, Board of Trustees. Autocad Drafting and Design.',
    coursesTaught: ['Autocad Drafting and Design', 'Financial Stewardship'],
    imageUrl: '',
    email: 'aliba.trustee@pcm.ph',
    featured: false,
  },
  {
    id: 'fac-bot-marquez',
    name: 'Dra. Maria Kristina I. Marquez',
    title: 'Member, Board of Trustees',
    group: 'Board of Trustees',
    role: 'Board of Trustees',
    credentials: 'Doctor of Medicine - 2017, B.S. Medical Laboratory Science - 2021, B.A. Christian Education - 2008',
    degrees: [
      'Doctor of Medicine - 2017',
      'Bachelor of Science in Medical Laboratory Science - 2021',
      'Bachelor of Arts in Christian Education - 2008',
    ],
    bio: 'Member, Board of Trustees.',
    coursesTaught: ['Medical Missions & Healthcare Ministry', 'Christian Education Principles'],
    imageUrl: '',
    email: 'marquez.trustee@pcm.ph',
    featured: false,
  },
  {
    id: 'fac-bot-suello',
    name: 'Reynaldo Suello',
    title: 'Member, Board of Trustees',
    group: 'Board of Trustees',
    role: 'Board of Trustees',
    credentials: 'Member, Board of Trustees',
    degrees: ['Member, Board of Trustees'],
    bio: 'Member, Board of Trustees.',
    coursesTaught: ['Church Leadership & Governance'],
    imageUrl: '',
    email: 'suello.trustee@pcm.ph',
    featured: false,
  },
  {
    id: 'fac-bot-hong',
    name: 'Dr. Stephen Anthony Hong',
    title: 'Member, Board of Trustees. Former President & Faculty Member',
    group: 'Board of Trustees',
    role: 'Board of Trustees & Former President',
    credentials: 'Doctor of Ministry (APTS), Master of Divinity (APTS), Bachelor-Church Growth/Mission (Pacific Christian College/Hope International Univ.)',
    degrees: [
      'Bachelor-Church Growth/Mission - Pacific Christian College/Hope International University',
      'Master of Divinity - Asia Pacific Theological Seminary',
      'Doctor of Ministry - Asia Pacific Theological Seminary',
    ],
    bio: 'Member, Board of Trustees. Former President & Faculty Member.',
    coursesTaught: ['Church Growth & Mission Strategy', 'Pastoral Theology', 'Advanced Leadership'],
    imageUrl: '',
    email: 'hong.trustee@pcm.ph',
    featured: true,
  },
  {
    id: 'fac-bot-dungo',
    name: 'Engr. Victor Dungo',
    title: 'Member, Board of Trustees',
    group: 'Board of Trustees',
    role: 'Board of Trustees',
    credentials: 'Engr., Member of the Board of Trustees',
    degrees: ['Bachelor of Science in Engineering'],
    bio: 'Member, Board of Trustees.',
    coursesTaught: ['Campus Infrastructure Stewardship'],
    imageUrl: '',
    email: 'dungo.trustee@pcm.ph',
    featured: false,
  },
  {
    id: 'fac-pasion',
    name: 'Arnulfo "Arnold" Pasion',
    title: 'Interim President',
    group: 'Administration',
    role: 'Interim President',
    credentials: 'Master of Divinity (APTS 2007), M.Min. (Manila Bible Seminary 1997), ABTheo (2019), B.Th./BSL (Aparri Bible Seminary 1985)',
    degrees: [
      'Bachelor of Arts in Theology (ABTheo) 2019',
      'B.Th./BSL, Aparri Bible Seminary, 1985',
      'M.Min., Manila Bible Seminary, 1997',
      'Master of Divinity, Asia Pacific Theological Seminary, 2007.',
    ],
    bio: 'Interim President. Faculty member since 1993.',
    coursesTaught: ['Systematic Theology', 'Biblical Exegesis', 'Pastoral Ministry & Homiletics'],
    imageUrl: '',
    email: 'president@pcm.ph',
    featured: true,
  },
  {
    id: 'fac-cruz',
    name: 'Benilda H. Cruz',
    title: 'Business Administrator, Volunteer (CPA)',
    group: 'Administration',
    role: 'Business Administrator',
    credentials: 'Bachelor of Science in Commerce, CPA (Philippines), CPA (California, USA)',
    degrees: [
      'Bachelor of Science in Commerce',
      'Certified Public Accountant (Philippines)',
      'Certified Public Accountant (California, USA)',
    ],
    bio: 'Business Administrator, Volunteer (CPA). Business Administrator.',
    coursesTaught: ['Institutional Business Administration', 'Financial Accountability & Stewardship'],
    imageUrl: '',
    email: 'business.admin@pcm.ph',
    featured: true,
  },
  {
    id: 'fac-santos-crisanta',
    name: 'Crisanta M. Santos',
    title: 'Academic Dean and Professor',
    group: 'Administration',
    role: 'Academic Dean and Professor',
    credentials: 'MDA (2020), ABTheo (2017), MAMin. (2010), ABCom. (1997)',
    degrees: [
      'Master of Development Administration Major in Public Administration (MDA) 2020',
      'Bachelor of Arts in Theology (ABTheo) 2017',
      'Masters of Arts in Ministry (MAMin.) 2010',
      'Bachelor of Arts in Communication (ABCom.) 1997',
    ],
    subjectTaught: ['General Education Subjects'],
    coursesTaught: ['General Education Subjects', 'Christian Ministry & Administration', 'Communication for Ministry'],
    bio: 'Academic Dean and Professor.',
    imageUrl: '',
    email: 'academic.dean@pcm.ph',
    featured: true,
  },
  {
    id: 'fac-benalio-marlon',
    name: 'Marlon T. Benalio',
    title: 'School Librarian',
    group: 'Faculty',
    role: 'School Librarian & Instructor',
    credentials: 'MAEd-EM (2020), MLIS (2016), BSE-Library Science (2005)',
    degrees: [
      'Master of Arts in Education major in Educational Management (MAEd-EM) 2020',
      'Master of Library and Information Science (MLIS) 2016',
      'Bachelor of Secondary Education major in Library Science (BSE-Library Science) 2005',
    ],
    subjectTaught: [
      'General Education Subjects',
      'Professional Education Subjects',
      'Senior High School Subjects',
    ],
    coursesTaught: [
      'General Education Subjects',
      'Professional Education Subjects',
      'Senior High School Subjects',
    ],
    bio: 'School Librarian. Instructs General Education Subjects, Professional Education Subjects, and Senior High School Subjects.',
    imageUrl: '',
    email: 'library@pcm.ph',
    featured: false,
  },
  {
    id: 'fac-cabalar',
    name: 'Judy G. Cabalar',
    title: 'Registrar and Instructor',
    group: 'Administration',
    role: 'Registrar and Instructor',
    credentials: 'MAED-EAS (In Progress), ABTheo (2018), MAMin. (2013), B.Th. (2008)',
    degrees: [
      'Master of Education Major in Educational Administration & Supervision (MAED-EAS) in Progress...',
      'Bachelor of Arts in Theology (ABTheo) - 2018',
      'Master of Arts in Ministry (Non-CHED) - 2013',
      'Bachelor of Science in Secondary Education (Undergraduate)',
      'Bachelor of Theology (Non-CHED) - 2008',
    ],
    subjectTaught: [
      'General Education Subjects',
      'Senior High School Subjects',
    ],
    coursesTaught: [
      'General Education Subjects',
      'Senior High School Subjects',
    ],
    bio: 'Registrar and Instructor.',
    imageUrl: '',
    email: 'registrar@pcm.ph',
    featured: true,
  },
  {
    id: 'fac-dagasen',
    name: 'Blessildo G. Dagasen',
    title: 'Professor',
    group: 'Faculty',
    role: 'Professor',
    credentials: 'Ph.D. in Philosophy (In progress), MST (2013), M.Div. (2006), Ph.B. (2003)',
    degrees: [
      'Doctor of Philosophy in Philosophy (Ph.D.) - In progress',
      'Master of Science in Theology (MST) - 2013',
      'Master of Divinity (MDiv.) - 2006',
      'Bachelor of Philosophy (PhB) 2003',
    ],
    subjectTaught: ['Biblical Subjects'],
    coursesTaught: ['Biblical Subjects', 'Philosophical Theology & Hermeneutics'],
    bio: 'Professor. Specializes in Biblical Subjects.',
    imageUrl: '',
    email: 'dagasen@pcm.ph',
    featured: true,
  },
  {
    id: 'fac-intuya',
    name: 'George C. Intuya',
    title: 'Professor',
    group: 'Faculty',
    role: 'Professor',
    credentials: 'Doctor of Philosophy (In progress), Th.M. (2012), M.Div. (2006), ABTheo (2003)',
    degrees: [
      'Doctor of Philosophy (In progress)',
      'Master of Theology (Th.M.) - 2012',
      'Master of Divinity (MDiv) - 2006',
      'Bachelor of Arts in Theology (ABTheo) - 2003',
    ],
    subjectTaught: [
      'Biblical Subjects',
      'General Subjects',
    ],
    coursesTaught: [
      'Biblical Subjects',
      'General Subjects',
    ],
    bio: 'Professor. Instructs Biblical Subjects and General Subjects.',
    imageUrl: '',
    email: 'intuya@pcm.ph',
    featured: true,
  },
  {
    id: 'fac-agayao',
    name: 'Julius Ceasar C. Agayao',
    title: 'Dean of Student Affairs; Course Facilitator; MDP Director; NSTP Coordinator',
    group: 'Administration',
    role: 'Dean of Student Affairs; Course Facilitator',
    credentials: 'MARS Unit Earner, ABTheo (2017), B.S.Ed. Major in PEHM (2011)',
    degrees: [
      'Master of Arts in Religious Education (MARS) Unit earner',
      'Bachelor of Arts in Theology (ABTheo) - 2017',
      'Bachelor of Arts in Secondary Education Major in PEHM - 2011',
    ],
    subjectTaught: [
      'Practical Subjects',
      'General Education Subjects',
    ],
    coursesTaught: [
      'Practical Subjects',
      'General Education Subjects',
      'Ministerial Discipleship Program (MDP)',
      'NSTP Coordination',
    ],
    bio: 'Dean of Student Affairs; Course Facilitator; MDP Director; NSTP Coordinator.',
    imageUrl: '',
    email: 'studentaffairs@pcm.ph',
    featured: true,
  },
  {
    id: 'fac-benalio-adelaida',
    name: 'Adelaida H. Benalio',
    title: 'Course Facilitator; Library Worker',
    group: 'Faculty',
    role: 'Course Facilitator; Library Worker',
    credentials: 'MAG (In progress), ABTheo (2017)',
    degrees: [
      'Master of Arts in Guidance (MAG) in progress..',
      'Bachelor of Arts in Theology (ABTheo) (2017)',
    ],
    subjectTaught: ['General Education Subjects'],
    coursesTaught: ['General Education Subjects', 'Guidance & Student Formation'],
    bio: 'Course Facilitator; Library Worker. Instructs General Education Subjects.',
    imageUrl: '',
    email: 'abenalio@pcm.ph',
    featured: false,
  },
  {
    id: 'fac-virtudazo',
    name: 'Elmer C. Virtudazo',
    title: 'Course Facilitator; Staff of Finance and Administrative Office',
    group: 'Faculty',
    role: 'Course Facilitator; Staff of Finance & Admin',
    credentials: 'MAFIL (In progress), ABTheo (2017)',
    degrees: [
      'Master of Arts in Filipino (MAFIL) - In progress.',
      'Bachelor of Arts in Theology (ABTheo) - 2017',
    ],
    subjectTaught: [
      'Practical Subject',
      'General Education Subject',
    ],
    coursesTaught: [
      'Practical Subject',
      'General Education Subject',
    ],
    bio: 'Course Facilitator; Staff of Finance and Administrative Office.',
    imageUrl: '',
    email: 'evirtudazo@pcm.ph',
    featured: false,
  },
  {
    id: 'fac-bacuyag',
    name: 'Emeliza Joy P. Bacuyag',
    title: 'Finance Officers; Course Facilitator',
    group: 'Faculty',
    role: 'Finance Officer; Course Facilitator',
    credentials: 'MAG (In progress), ABTheo (2018), B.Th. (2010)',
    degrees: [
      'Master of Arts in Guidance (MAG) In progress',
      'Bachelor of Arts in Theology (ABTheo) - 2018',
      'Bachelor of Theology - 2010',
    ],
    subjectTaught: ['Biblical Language'],
    coursesTaught: ['Biblical Language'],
    bio: 'Finance Officers; Course Facilitator. Instructs Biblical Language.',
    imageUrl: '',
    email: 'ebacuyag@pcm.ph',
    featured: false,
  },
  {
    id: 'fac-huckaba-james',
    name: 'Dr. James A. Huckaba',
    title: 'Academic Dean Emeritus',
    group: 'Emeritus & Adjunct',
    role: 'Academic Dean Emeritus & Adjunct Professor',
    credentials: 'Th.D. (Southern Seminary 1977), M.Div. (Western Seminary 1972), B.Th. (Northwest Christian College 1969), Tel Aviv Univ. (1981)',
    degrees: [
      'Bachelor of Theology Northwest Christian College, 1969',
      'MDiv. Western Seminary, 1972',
      'ThD Southern Seminary, 1977',
      'Additional Academic Work at the Univ. of Tel Aviv, 1981, Western Seminary, 1989-1990.',
    ],
    subjectTaught: ['Adjunct Professor of Languages, Homiletics'],
    coursesTaught: [
      'Adjunct Professor of Languages, Homiletics',
      'Biblical Greek Grammar & Exegesis',
      'Expository Preaching (Homiletics)',
    ],
    bio: 'Academic Dean Emeritus. Adjunct Professor of Languages, Homiletics.',
    imageUrl: '',
    email: 'academic.emeritus@pcm.ph',
    featured: true,
  },
  {
    id: 'fac-lubag-samson',
    name: 'Dr. Samson B. Lubag',
    title: 'Adjunct Professor',
    group: 'Emeritus & Adjunct',
    role: 'Founding President (1992) & Adjunct Professor',
    credentials: 'D.Min. (Emmanuel Christian Seminary 1999), Ed.D. (Univ. of Baguio 1994), M.Div. (1991), MPA (1985), BBA (1981), B.A. (1980), B.Th. (1976)',
    degrees: [
      'Doctor of Ministry (D. Min.), formerly Emmanuel School of Religion but now Emmanuel Christian Seminary, 1999.',
      'Doctor of Education (Ed.D.), University of Baguio Graduate School, 1994.',
      'Master of Divinity, formerly Emmanuel School of Religion but now Emmanuel Christian Seminary, 1991.',
      'Master of Public Administration, University of Manila, 1985.',
      'Bachelor of Business Administration in Management, University of Manila, 1981.',
      'Bachelor of Arts in English Literature, University of Manila, 1980.',
      'Bachelor of Theology, Manila Bible Seminary, 1976.',
    ],
    bio: 'Adjunct Professor. Founding President (1992).',
    coursesTaught: [
      'Pastoral Leadership & Administration',
      'Restoration Movement History',
      'Advanced Homiletics & Ministry Ethics',
    ],
    imageUrl: '',
    email: 'slubag@pcm.ph',
    featured: true,
  },
];

export const INITIAL_TESTIMONIALS: Testimonial[] = [
  {
    id: 't-1',
    name: 'Pastor Joshua Mendoza',
    role: 'Senior Pastor & Church Planter',
    category: 'Alumni',
    quote:
      'My four years at PCM in the Bachelor of Theology program forged not only my biblical knowledge through Greek and Hebrew, but more importantly, my shepherd’s heart. The professors did not just lecture; they prayed over us, mentored us in our struggles, and taught us to preach the uncompromised Word of God with tears and conviction.',
    programOrMinistry: 'B.Th. Class of 2018 | Grace Bible Church, Cavite',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 't-2',
    name: 'Charisse Anne Reyes',
    role: 'Third-Year Student & Youth Coordinator',
    category: 'Student',
    quote:
      'Studying at PCM is life-transforming. The community life, daily chapel worship, and hands-on practicum assignments in urban poor communities have stretched my faith beyond what I could imagine. I feel equipped and confident to step into full-time ministry.',
    programOrMinistry: 'Bachelor of Christian Ministry (B.C.M.) | Current Student',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 't-3',
    name: 'Bishop Rolando Santos',
    role: 'General Overseer, Alliance of Evangelical Churches',
    category: 'Ministry Leader',
    quote:
      'Whenever our denomination receives graduates from Philippine College of Ministry, we know they come with doctrinal soundness, humble servanthood, and genuine practical competence. PCM remains one of the most trusted theological institutions in the nation.',
    programOrMinistry: 'Partner Denominational Leader',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 't-4',
    name: 'Atty. Mark Vincent Lim',
    role: 'Marketplace Minister & Church Elder',
    category: 'Alumni',
    quote:
      'The Master of Christian Leadership modular program allowed me to continue my legal practice while gaining profound biblical depth in organizational governance and ethical leadership. It helped me bridge the sacred-secular divide.',
    programOrMinistry: 'Master of Christian Leadership (M.C.L.) | Class of 2022',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=400&auto=format&fit=crop',
  },
];

export const INITIAL_STATS: ImpactStat[] = [
  {
    id: 'stat-1',
    value: '24+',
    label: 'Years of Ministry Excellence',
    description: 'Providing faithful, Christ-centered theological education since 2002.',
    iconName: 'Award',
  },
  {
    id: 'stat-2',
    value: '650+',
    label: 'Graduates & Active Alumni',
    description: 'Pastoring churches, planting congregations, and serving in 18 countries.',
    iconName: 'GraduationCap',
  },
  {
    id: 'stat-3',
    value: '85+',
    label: 'Partner Churches & Missions',
    description: 'Collaborating for hands-on student practicum and pastoral apprenticeships.',
    iconName: 'Church',
  },
  {
    id: 'stat-4',
    value: '100%',
    label: 'Biblical & Doctrinal Fidelity',
    description: 'Unwavering commitment to the inerrancy and sufficiency of the Holy Scriptures.',
    iconName: 'BookOpen',
  },
];

export const INITIAL_APPLICATIONS: AdmissionApplication[] = [
  {
    id: 'app-001',
    referenceNumber: 'PCM-2026-8941',
    createdAt: '2026-08-20T10:30:00Z',
    updatedAt: '2026-08-22T14:15:00Z',
    status: 'Under Review',
    programId: 'prog-bth',
    programName: 'Bachelor of Theology (B.Th.)',
    studyMode: 'On-Campus Full-Time',
    fullName: 'Gabriel Miguel Dela Cruz',
    email: 'gabriel.delacruz@gmail.com',
    phone: '+63 917 555 0192',
    birthDate: '2004-03-15',
    gender: 'Male',
    civilStatus: 'Single',
    citizenship: 'Filipino',
    address: '124 Malakas St., Brgy. Central',
    city: 'Quezon City',
    province: 'Metro Manila',
    salvationYear: '2019',
    waterBaptized: true,
    homeChurch: 'Christ Fellowship Bible Church',
    churchDenomination: 'Evangelical Free / Baptist',
    pastorName: 'Rev. Arnold Santos',
    pastorContact: '+63 918 222 3344',
    currentMinistryInvolvement: 'Youth Bible Study Leader & Worship Acoustic Guitarist',
    personalTestimony:
      'I accepted Jesus Christ as my personal Lord and Savior during our 2019 youth camp. Over the past four years, God has deeply burdened my heart for biblical teaching and preaching God’s uncompromised Word to youth and families in urban communities.',
    callingStatement:
      'I feel a clear calling into pastoral ministry and church planting in provincial areas of Luzon where sound biblical churches are scarce.',
    highestEducation: 'Senior High School (HUMSS Strand)',
    previousSchool: 'Quezon City Science High School',
    yearGraduated: '2024',
    gpaOrHonors: 'With High Honors (92.5%)',
    documents: {
      idPhoto: true,
      transcriptOfRecords: true,
      pastoralRecommendation: true,
      personalTestimonyDoc: true,
      birthCertificate: true,
    },
    internalNotes: [
      'Passed English & Bible exam with 94% score.',
      'Pastor Arnold gave an outstanding character reference.',
      'Scheduled for Dean’s panel interview on Sept 2.',
    ],
  },
  {
    id: 'app-002',
    referenceNumber: 'PCM-2026-8942',
    createdAt: '2026-08-24T08:15:00Z',
    updatedAt: '2026-08-25T11:00:00Z',
    status: 'Accepted',
    programId: 'prog-mdiv',
    programName: 'Master of Divinity (M.Div.)',
    studyMode: 'Modular / Hybrid',
    fullName: 'Hannah Grace Villanueva-Tan',
    email: 'hannah.tan@yahoo.com',
    phone: '+63 920 444 8811',
    birthDate: '1995-11-20',
    gender: 'Female',
    civilStatus: 'Married',
    citizenship: 'Filipino',
    address: 'Block 5 Lot 12, San Jose Heights',
    city: 'Antipolo',
    province: 'Rizal',
    salvationYear: '2011',
    waterBaptized: true,
    homeChurch: 'Living Hope Christian Church',
    churchDenomination: 'Christian & Missionary Alliance',
    pastorName: 'Pastor Joel Tan',
    pastorContact: '+63 917 888 1234',
    currentMinistryInvolvement: 'Women’s Discipleship Director & Sunday School Teacher',
    personalTestimony:
      'Growing up in a Christian home, my personal encounter with Christ happened during college. God called me to equip women and youth in deeper theological understanding.',
    callingStatement:
      'Seeking to teach in Bible institutes and develop biblical counseling frameworks for traumatized families.',
    highestEducation: 'Bachelor of Science in Psychology',
    previousSchool: 'University of Santo Tomas',
    yearGraduated: '2017',
    gpaOrHonors: 'Cum Laude (1.45)',
    documents: {
      idPhoto: true,
      transcriptOfRecords: true,
      pastoralRecommendation: true,
      personalTestimonyDoc: true,
      birthCertificate: true,
    },
    internalNotes: ['Application fully accepted. Scholarship 50% approved for pastoral workers.'],
  },
  {
    id: 'app-003',
    referenceNumber: 'PCM-2026-8943',
    createdAt: '2026-08-27T16:20:00Z',
    updatedAt: '2026-08-27T16:20:00Z',
    status: 'Submitted',
    programId: 'prog-bcm',
    programName: 'Bachelor of Christian Ministry (B.C.M.)',
    studyMode: 'On-Campus Full-Time',
    fullName: 'John Patrick Alcantara',
    email: 'jp.alcantara@gmail.com',
    phone: '+63 908 777 4433',
    birthDate: '2005-07-08',
    gender: 'Male',
    civilStatus: 'Single',
    citizenship: 'Filipino',
    address: '45 Acacia Avenue, Villa Mercedes',
    city: 'San Fernando',
    province: 'Pampanga',
    salvationYear: '2021',
    waterBaptized: true,
    homeChurch: 'Grace & Truth Baptist Church',
    churchDenomination: 'Baptist',
    pastorName: 'Rev. Danilo Alcantara',
    pastorContact: '+63 919 333 5566',
    currentMinistryInvolvement: 'Youth Outreach Worker & Sound Technician',
    personalTestimony: 'Saved by God’s marvelous grace from worldly influences in 2021.',
    callingStatement: 'Desiring to learn discipleship leadership and plant rural youth centers.',
    highestEducation: 'High School Graduate',
    previousSchool: 'Pampanga High School',
    yearGraduated: '2025',
    documents: {
      idPhoto: true,
      transcriptOfRecords: true,
      pastoralRecommendation: true,
      personalTestimonyDoc: true,
      birthCertificate: false,
    },
  },
];

export const DEMO_STUDENT_PROFILE: StudentProfile = {
  id: 'std-2024-0418',
  studentId: '2024-PCM-0418',
  fullName: 'Elijah Matthew Soriano',
  email: 'elijah.soriano@student.pcm.edu.ph',
  program: 'Bachelor of Theology (B.Th.)',
  yearLevel: '3rd Year (Junior)',
  currentSemester: '1st Semester, AY 2026–2027',
  academicYear: '2026–2027',
  gpa: 3.82,
  totalUnitsEarned: 78,
  mentorName: 'Dr. Jonathan Reyes, Ph.D.',
  homeChurch: 'Christ Redeemer Evangelical Church, Pasig',
  avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=400&auto=format&fit=crop',
  tuitionTotal: 26100,
  tuitionPaid: 20000,
  courses: [
    {
      id: 'sc-1',
      code: 'THE-301',
      title: 'Systematic Theology II (Christology & Soteriology)',
      units: 3,
      schedule: 'Mon / Wed 8:30 AM – 10:00 AM',
      room: 'Theology Hall 102',
      instructor: 'Dr. Emmanuel Santos',
      midtermGrade: 1.25,
      finalGrade: 1.25,
      status: 'In Progress',
    },
    {
      id: 'sc-2',
      code: 'GRK-201',
      title: 'Greek Syntax & Exegetical Methods',
      units: 3,
      schedule: 'Tue / Thu 10:30 AM – 12:00 PM',
      room: 'Language Lab 204',
      instructor: 'Rev. Ruben Alcantara',
      midtermGrade: 1.5,
      finalGrade: 1.5,
      status: 'In Progress',
    },
    {
      id: 'sc-3',
      code: 'HOM-301',
      title: 'Expository Preaching & Homiletics',
      units: 3,
      schedule: 'Wed 1:30 PM – 4:30 PM',
      room: 'Grace Chapel Studio',
      instructor: 'Pastor David Tan',
      midtermGrade: 1.0,
      finalGrade: 1.25,
      status: 'In Progress',
    },
    {
      id: 'sc-4',
      code: 'PAS-301',
      title: 'Pastoral Ministry & Church Administration',
      units: 3,
      schedule: 'Fri 8:30 AM – 11:30 AM',
      room: 'Leadership Center 301',
      instructor: 'Dr. Benjamin Villanueva',
      midtermGrade: 1.25,
      finalGrade: 1.0,
      status: 'In Progress',
    },
    {
      id: 'sc-5',
      code: 'PRA-301',
      title: 'Ministry Practicum III (Pulpit & Pastoral Apprenticeship)',
      units: 2,
      schedule: 'Weekend Field Assignment (Sat/Sun)',
      room: 'Partner Church Assignment',
      instructor: 'Pastor David Tan',
      midtermGrade: 1.0,
      finalGrade: 1.0,
      status: 'In Progress',
    },
  ],
  practicumEntries: [
    {
      id: 'prac-1',
      date: '2026-08-23',
      ministryType: 'Preaching / Teaching',
      location: 'Faith Community Bible Church, Antipolo',
      hours: 6,
      description:
        'Preached Sunday morning message on Romans 8:28–39 ("More Than Conquerors"). Facilitated afternoon youth leadership debrief.',
      supervisorName: 'Pastor Ronald Bautista',
      status: 'Approved',
    },
    {
      id: 'prac-2',
      date: '2026-08-16',
      ministryType: 'Counseling & Visitation',
      location: 'Barangay San Antonio, Pasig City',
      hours: 4,
      description:
        'Accompanied senior deacon for home visitation of elderly church members and hospital prayer for brother recovering from surgery.',
      supervisorName: 'Deacon Jerry Mendoza',
      status: 'Approved',
    },
    {
      id: 'prac-3',
      date: '2026-08-09',
      ministryType: 'Evangelism & Outreach',
      location: 'Cainta Floodway Community Outreach Center',
      hours: 5,
      description:
        'Led Bible storytelling and gospel tracts distribution for 45 children and their parents during feeding ministry.',
      supervisorName: 'Sister Grace Evangelista',
      status: 'Approved',
    },
  ],
};

export const INITIAL_DOWNLOADS: DownloadableResource[] = [
  {
    id: 'dl-1',
    title: 'PCM Official Academic Prospectus & Course Catalog (2026–2027)',
    category: 'Prospectus',
    fileSize: '4.8 MB',
    format: 'PDF',
    downloadCount: 1420,
    description:
      'Complete degree overviews, course syllabi outlines, faculty roster, campus facilities, and academic regulations.',
  },
  {
    id: 'dl-2',
    title: 'PCM Official Student Handbook & Code of Conduct',
    category: 'Student Handbook',
    fileSize: '2.1 MB',
    format: 'PDF',
    downloadCount: 890,
    description:
      'Guidelines on spiritual formation, chapel attendance, academic integrity, library use, and dormitory policies.',
  },
  {
    id: 'dl-3',
    title: 'Pastoral Recommendation & Church Endorsement Form',
    category: 'Application Form',
    fileSize: '450 KB',
    format: 'PDF',
    downloadCount: 2310,
    description:
      'Official confidential evaluation form to be completed by the applicant’s home church pastor or governing elder board.',
  },
  {
    id: 'dl-4',
    title: 'Official Academic Calendar AY 2026–2027 (Semestral & Modular)',
    category: 'Academic Calendar',
    fileSize: '680 KB',
    format: 'PDF',
    downloadCount: 1150,
    description:
      'Key semestral dates including enrollment, midterms, final examinations, spiritual retreats, and graduation rites.',
  },
  {
    id: 'dl-5',
    title: 'Veritas et Ministerium (PCM Theological Journal, Vol. XII)',
    category: 'Journal',
    fileSize: '6.2 MB',
    format: 'PDF',
    downloadCount: 780,
    description:
      'Peer-reviewed theological articles by PCM faculty on Philippine church history, expository preaching, and cultural apologetics.',
  },
  {
    id: 'dl-6',
    title: 'Ministry Practicum Field Manual & Supervisor Logbook',
    category: 'Practicum Manual',
    fileSize: '1.4 MB',
    format: 'PDF',
    downloadCount: 620,
    description:
      'Guide for students, field mentors, and partner church supervisors detailing required ministry hours and competency rubrics.',
  },
];

export const INITIAL_SERMONS: SermonLecture[] = [
  {
    id: 'serm-1',
    title: 'The Inerrant Word: Our Anchor in Shifting Cultural Winds',
    speaker: 'Dr. Benjamin Villanueva',
    series: 'Convocation & Presidential Lectures 2026',
    date: 'August 14, 2026',
    duration: '48 mins',
    passage: '2 Timothy 3:14–17; Psalm 19:7–11',
    category: 'Chapel Service',
    description:
      'An inspiring exposition on why ministerial durability hinges solely on unwavering confidence in the divine inspiration, total truthfulness, and supreme authority of the Holy Scriptures.',
  },
  {
    id: 'serm-2',
    title: 'The Shepherd’s Heart: Tend the Flock of God with Humility',
    speaker: 'Dr. Emmanuel Santos',
    series: 'Pastoral Ministry & Shepherding',
    date: 'July 30, 2026',
    duration: '52 mins',
    passage: '1 Peter 5:1–5',
    category: 'Theology Lecture',
    description:
      'A powerful pastoral charge examining Peter’s exhortations to elders against domineering leadership and towards joyful, sacrificial servant-heartedness.',
  },
  {
    id: 'serm-3',
    title: 'Covenant Fidelity: The God Who Keeps His Promises',
    speaker: 'Dr. Jonathan Reyes',
    series: 'Old Testament Theological Themes',
    date: 'July 16, 2026',
    duration: '44 mins',
    passage: 'Genesis 15:1–21; Hebrews 6:13–20',
    category: 'Theology Lecture',
    description:
      'Tracing God’s unilateral covenant with Abraham to its climax in the blood of Jesus Christ, providing unshakable assurance for Christian ministers in trials.',
  },
  {
    id: 'serm-4',
    title: 'Sent Into the Harvest: The Great Commission in Southeast Asia',
    speaker: 'Rev. Ruben Alcantara',
    series: 'Missions Emphasis Week',
    date: 'June 25, 2026',
    duration: '40 mins',
    passage: 'Matthew 28:18–20; Romans 10:14–17',
    category: 'Chapel Service',
    description:
      'Examining the unreached peoples of Southeast Asia and the urgent role of Philippine churches and seminaries in sending cross-cultural missionaries.',
  },
];

export const INITIAL_FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    category: 'Admissions',
    question: 'What are the basic admission requirements for the Bachelor of Theology (B.Th.) program?',
    answer:
      'Applicants must be born-again Christians with a clear testimony of faith, high school diploma / Form 138 (or equivalent), endorsement letter from their home church senior pastor, passing score on the PCM entrance assessment (Bible knowledge & English comprehension), and a completed admissions interview with our faculty panel.',
  },
  {
    id: 'faq-2',
    category: 'Academics',
    question: 'Are PCM degrees recognized and accredited?',
    answer:
      'Yes. PCM operates with recognition and adheres to the standards of the Asia Theological Association (ATA) and the Association of Christian Schools, Colleges, and Universities (ACSCU), ensuring our graduates are recognized by major evangelical denominations, mission agencies, and international theological graduate schools.',
  },
  {
    id: 'faq-3',
    category: 'Financial & Scholarships',
    question: 'What scholarships and financial assistance are available at PCM?',
    answer:
      'PCM believes financial constraints should not hinder God’s calling. We provide Pastoral Worker Grants (up to 50% tuition discount for children of full-time pastors and missionaries), Academic Honor Scholarships (for valedictorians and high honors students), Work-Study Grants on campus, and Church-Matching Sponsorships.',
  },
  {
    id: 'faq-4',
    category: 'Academics',
    question: 'Can I study modularly or online if I am working full-time or bi-vocational?',
    answer:
      'Yes! We offer flexible hybrid modular formats for our Master of Divinity (M.Div.), Master of Christian Leadership (M.C.L.), and Certificate in Biblical Studies (C.B.S.). Intensive modules meet on selected weekends, evenings, or concentrated one-week resident blocks with asynchronous online support.',
  },
  {
    id: 'faq-5',
    category: 'Student Life',
    question: 'Does PCM provide student dormitories and meal plans on campus?',
    answer:
      'Yes. PCM maintains secure, air-conditioned and standard resident dormitories for male and female single students on our Quezon City campus, featuring high-speed study lounges, devotional prayer rooms, dining hall meal plans, and campus fellowship spaces.',
  },
  {
    id: 'faq-6',
    category: 'Spiritual Formation',
    question: 'What role does Spiritual Formation and Chapel play in the curriculum?',
    answer:
      'Spiritual formation is at the core of PCM. All full-time students participate in weekly community chapel services, small-group faculty mentorship pods, semestral prayer retreats, and supervised weekend ministry practicum to cultivate prayerful intimacy with God alongside academic studies.',
  },
];

export const INITIAL_ADMIN_USERS: AdminUser[] = [
  {
    id: 'adm-1',
    name: 'Dr. Benjamin Villanueva',
    email: 'president@pcm.edu.ph',
    role: 'Super Admin',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop',
    department: 'Office of the President & Chancellor',
  },
  {
    id: 'adm-2',
    name: 'Dr. Emmanuel Santos',
    email: 'academics@pcm.edu.ph',
    role: 'Academic Staff',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
    department: 'Academic Affairs & Faculty Council',
  },
  {
    id: 'adm-3',
    name: 'Ms. Rebecca Santos-Alvarez',
    email: 'admissions@pcm.edu.ph',
    role: 'Admissions Staff',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop',
    department: 'Office of the Registrar & Admissions',
  },
  {
    id: 'adm-4',
    name: 'Pastor Joel Bautista',
    email: 'media@pcm.edu.ph',
    role: 'Content Manager',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=200&auto=format&fit=crop',
    department: 'Public Relations, Media & Website CMS',
  },
];

export const INITIAL_SCRAPBOOK: ScrapbookItem[] = [
  {
    id: 'sb-1',
    title: 'Lamtang Campus Main Building & Cordillera Mountain View',
    category: 'Campus Life & Lamtang',
    imageUrl: 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?q=80&w=1200&auto=format&fit=crop',
    date: 'June 2025',
    year: '2025',
    location: 'Lamtang, Puguis, La Trinidad, Benguet',
    caption:
      'The peaceful hillside campus of Philippine College of Ministry overlooking the cool, misty pine ridges of Benguet. Acquired in Dec 2002 and operating since June 13, 2005.',
    tags: ['Campus', 'Lamtang', 'La Trinidad', 'Benguet', 'Facilities'],
  },
  {
    id: 'sb-2',
    title: 'Weekly Community Chapel Worship & Praise',
    category: 'Chapel & Worship',
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1200&auto=format&fit=crop',
    date: 'August 2025',
    year: '2025',
    location: 'PCM Main Chapel Hall',
    caption:
      'Faculty and students gathering for weekly corporate worship, student-led acoustic praise, and inspiring expositions of God’s inerrant Word.',
    tags: ['Chapel', 'Worship', 'Praise', 'Spiritual Formation'],
  },
  {
    id: 'sb-3',
    title: 'Cordillera Mountain Evangelism & Medical Outreach',
    category: 'Missions & Outreach',
    imageUrl: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=1200&auto=format&fit=crop',
    date: 'April 2025',
    year: '2025',
    location: 'Mountain Province & Benguet Outlying Barangays',
    caption:
      'PCM student ministry teams trekking into rural Cordillera villages for children’s Vacation Bible School, gospel tracts distribution, and elderly home visits.',
    tags: ['Missions', 'Cordillera', 'Evangelism', 'Outreach', 'Practicum'],
  },
  {
    id: 'sb-4',
    title: '32nd Commencement Exercises & Baccalaureate Service',
    category: 'Graduation & Convocation',
    imageUrl: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?q=80&w=1200&auto=format&fit=crop',
    date: 'May 2025',
    year: '2025',
    location: 'PCM Amphitheater & Grace Chapel',
    caption:
      'Celebrating another batch of Bachelor of Theology, BTh SCM, and Associate graduates commissioned and sent forth to pastor churches across the Philippines and overseas.',
    tags: ['Graduation', 'Commencement', 'Alumni', 'Baccalaureate'],
  },
  {
    id: 'sb-5',
    title: 'Annual Semestral Spiritual Retreat & Prayer Camp',
    category: 'Retreats & Fellowship',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=1200&auto=format&fit=crop',
    date: 'September 2025',
    year: '2025',
    location: 'Camp John Hay & Mount Cabuyao Prayer Ridge',
    caption:
      'Unplugging from academic schedules for 48 hours of fasting, devotional silence, faculty mentorship circles, and earnest intercession for the Philippine harvest field.',
    tags: ['Retreat', 'Prayer', 'Fellowship', 'Mentorship'],
  },
  {
    id: 'sb-6',
    title: 'Historic Foundation Day at T. Alonzo Street (June 12, 1992)',
    category: 'Heritage & Pioneers',
    imageUrl: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?q=80&w=1200&auto=format&fit=crop',
    date: 'June 12, 1992',
    year: '1992',
    location: '140 T. Alonzo Street, Baguio City',
    caption:
      'Archival memory of the inaugural classes of Philippine College of Ministry led by founding President Rev. Samson Lubag, Dennis McKinney, and pioneer missionary instructors.',
    tags: ['History', 'Founders', '1992', 'Samson Lubag', 'Heritage'],
  },
  {
    id: 'sb-7',
    title: 'Senior High School GAS Cultural Fellowship & Sportsfest',
    category: 'Campus Life & Lamtang',
    imageUrl: 'https://images.unsplash.com/photo-1526976668912-1a811878dd37?q=80&w=1200&auto=format&fit=crop',
    date: 'November 2025',
    year: '2025',
    location: 'PCM Campus Grounds & Court',
    caption:
      'Senior High School General Academic Strand students showcasing indigenous Cordillera dances, fellowship games, and team-building camaraderie.',
    tags: ['Senior High', 'GAS', 'Sportsfest', 'Culture', 'Campus Life'],
  },
  {
    id: 'sb-8',
    title: 'Theological Library & Greek Exegesis Study Circles',
    category: 'Campus Life & Lamtang',
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?q=80&w=1200&auto=format&fit=crop',
    date: 'October 2025',
    year: '2025',
    location: 'PCM James Huckaba Memorial Library',
    caption:
      'Students engaging in collaborative original language translations, reading historic commentaries, and preparing sermons in the quiet library stacks.',
    tags: ['Library', 'Greek', 'Exegesis', 'Academics', 'Study'],
  },
  {
    id: 'sb-9',
    title: 'Pastoral Practicum Pulpit Supply at Baguio City Partner Church',
    category: 'Missions & Outreach',
    imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=1200&auto=format&fit=crop',
    date: 'July 2025',
    year: '2025',
    location: 'Baguio City Church of Christ Fellowship',
    caption:
      '4th Year B.Th. intern delivering Sunday morning sermon under the mentorship of a seasoned local pastor.',
    tags: ['Practicum', 'Preaching', 'Local Church', 'Pulpit'],
  },
];

export const INITIAL_MIGRATION_AUDIT: MigrationAuditItem[] = [
  {
    id: 'audit-1',
    sourceUrl: 'https://pcm.ph/',
    targetPage: 'home',
    pageTitle: 'Home (Institutional Gateway)',
    status: 'MIGRATED',
    imagesCount: 14,
    documentsCount: 6,
    linksCount: 22,
    notes: 'Complete institutional overview, mission/vision, video gateway, quick stats, programs carousel, faculty spotlight, and CTA.',
    lastChecked: 'August 2026',
  },
  {
    id: 'audit-2',
    sourceUrl: 'https://pcm.ph/why-choose-pcm',
    targetPage: 'why-choose-pcm',
    pageTitle: 'Why Choose PCM',
    status: 'MIGRATED',
    imagesCount: 8,
    documentsCount: 3,
    linksCount: 12,
    notes: 'Preserved all 7 core institutional distinctions: Biblical fidelity, Cordillera/Baguio climate & retreat setting, affordable tuition with DepEd vouchers, practical apprenticeship, Restoration Movement heritage, caring community, and high alumni ministry placement.',
    lastChecked: 'August 2026',
  },
  {
    id: 'audit-3',
    sourceUrl: 'https://pcm.ph/about',
    targetPage: 'about',
    pageTitle: 'About Us',
    status: 'MIGRATED',
    imagesCount: 12,
    documentsCount: 4,
    linksCount: 18,
    notes: 'Complete 1992-present history (T. Alonzo St -> Ruff Hause Hotel -> Dec 2002 Lamtang 7500sqm acquisition -> June 13 2005 campus opening), Philippine Christian Mission Baguio team, Statement of Faith, Core Values, President message, and CHED/PABATS/PCEC accreditations.',
    lastChecked: 'August 2026',
  },
  {
    id: 'audit-4',
    sourceUrl: 'https://pcm.ph/academics',
    targetPage: 'academics',
    pageTitle: 'Academics & Curricula',
    status: 'MIGRATED',
    imagesCount: 10,
    documentsCount: 5,
    linksCount: 24,
    notes: 'Full coverage of Senior High GAS, Associate of Theology, Bachelor of Theology, BTh SCM Chaplaincy, Master of Divinity, Master of Christian Leadership, and Certificate programs with complete semester course tables.',
    lastChecked: 'August 2026',
  },
  {
    id: 'audit-5',
    sourceUrl: 'https://pcm.ph/admissions',
    targetPage: 'admissions',
    pageTitle: 'Admissions & Enrollment',
    status: 'MIGRATED',
    imagesCount: 6,
    documentsCount: 4,
    linksCount: 15,
    notes: '4-step admission procedure, entrance test details, DepEd SHS voucher guidelines, tuition calculator, downloadable recommendation forms, and live application submission portal.',
    lastChecked: 'August 2026',
  },
  {
    id: 'audit-6',
    sourceUrl: 'https://pcm.ph/faculty',
    targetPage: 'about / academics / faculty',
    pageTitle: 'Faculty & Administration',
    status: 'MIGRATED',
    imagesCount: 13,
    documentsCount: 2,
    linksCount: 16,
    notes: 'Full roster migrated including founders Samson Lubag, Dr. James Huckaba, Linda Huckaba, Prof. Gerwin Falla Castillo, Ma’am Crisanta, Sir Ronell, Rev. Bill Read, and modern leaders.',
    lastChecked: 'August 2026',
  },
  {
    id: 'audit-7',
    sourceUrl: 'https://pcm.ph/programs',
    targetPage: 'academics (Programs Filter)',
    pageTitle: 'Academic Programs Directory',
    status: 'MIGRATED',
    imagesCount: 9,
    documentsCount: 6,
    linksCount: 20,
    notes: 'Dynamic program directory with modal curriculum inspection, career pathways, credit breakdowns, and direct application routing.',
    lastChecked: 'August 2026',
  },
  {
    id: 'audit-8',
    sourceUrl: 'https://pcm.ph/scrapbook',
    targetPage: 'scrapbook',
    pageTitle: 'Scrapbook / Photo Gallery',
    status: 'MIGRATED',
    imagesCount: 24,
    documentsCount: 0,
    linksCount: 8,
    notes: 'Full-featured photo gallery with category filters (Campus Life & Lamtang, Chapel & Worship, Missions & Outreach, Graduation & Convocation, Retreats & Fellowship, Heritage & Pioneers), lightbox preview, date/location tags, and download capabilities.',
    lastChecked: 'August 2026',
  },
  {
    id: 'audit-9',
    sourceUrl: 'https://pcm.ph/contact',
    targetPage: 'contact',
    pageTitle: 'Contact Us & Campus Location',
    status: 'MIGRATED',
    imagesCount: 4,
    documentsCount: 1,
    linksCount: 10,
    notes: 'Lamtang, Puguis, La Trinidad, Benguet address, Baguio P.O. Box 298, phones +63 74 422 2577 / +63 917 582 1992, emails info@pcm.ph & pcmpresident1992@gmail.com, Google Maps interactive route, and direct contact inquiry form.',
    lastChecked: 'August 2026',
  },
  {
    id: 'audit-10',
    sourceUrl: 'https://pcm.ph/student-life',
    targetPage: 'student-life',
    pageTitle: 'Student Life & Campus Community',
    status: 'MIGRATED',
    imagesCount: 8,
    documentsCount: 2,
    linksCount: 14,
    notes: 'Spiritual formation, weekly chapel schedule, dormitories, dining hall, student council, intramurals, and Benguet mountain retreats.',
    lastChecked: 'August 2026',
  },
  {
    id: 'audit-11',
    sourceUrl: 'https://pcm.ph/ministry',
    targetPage: 'ministry',
    pageTitle: 'Ministry Practicum & Field Apprenticeships',
    status: 'MIGRATED',
    imagesCount: 7,
    documentsCount: 3,
    linksCount: 12,
    notes: '80+ church partner network, 300+ hour supervised internship requirements, hospital/prison chaplaincy field placements, and supervisor logbooks.',
    lastChecked: 'August 2026',
  },
  {
    id: 'audit-12',
    sourceUrl: 'https://pcm.ph/news-events',
    targetPage: 'news-events',
    pageTitle: 'News, Events & Announcements',
    status: 'MIGRATED',
    imagesCount: 12,
    documentsCount: 2,
    linksCount: 16,
    notes: 'Live institutional announcements, upcoming theological conferences, commencement dates, and search/filter mechanisms.',
    lastChecked: 'August 2026',
  },
  {
    id: 'audit-13',
    sourceUrl: 'https://pcm.ph/resources',
    targetPage: 'resources',
    pageTitle: 'Downloadable Resources & Sermons',
    status: 'MIGRATED',
    imagesCount: 6,
    documentsCount: 8,
    linksCount: 14,
    notes: 'Official Prospectus PDF, Student Handbook, pastoral recommendation forms, theological journal articles, and recorded chapel audio sermons.',
    lastChecked: 'August 2026',
  },
];

